language: php
sudo: false

php:
    - "7.2"
    - "7.1"
    - "7.0"
    - "5.6"
    - "5.5"
    - "hhvm"

matrix:
    fast_finish: true
    allow_failures:
        - php: "hhvm"

install:
    - composer self-update
    - composer update

script:
    - vendor/bin/phpunit
    - vendor/bin/psalm
    - vendor/bin/phpcs